language: java
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: target
  repo: eliotolhoek/eliotolhoek.github.io
  target_branch: master
  on:
    branch: master